"""Add voyage_films and streaming_platforms

Revision ID: 644a32ccbfd3
Revises: dd73ba439e53
Create Date: 2025-12-01 16:09:57.308340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '644a32ccbfd3'
down_revision = 'dd73ba439e53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voyage_films',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('destination', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('poster_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('streaming_platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('platform_name', sa.String(length=50), nullable=False),
    sa.Column('platform_url', sa.String(length=255), nullable=True),
    sa.Column('platform_logo', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['film_id'], ['voyage_films.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('streaming_platforms')
    op.drop_table('voyage_films')
    # ### end Alembic commands ###
