"""Add tmdb_id column and unique constraint (tmdb_id, mood_id)

Revision ID: 89e0f9f2aeb2
Revises: 644a32ccbfd3
Create Date: 2025-12-03 16:19:14.892811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89e0f9f2aeb2'
down_revision = '644a32ccbfd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tmdb_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_movies_tmdb_id'), ['tmdb_id'], unique=False)
        batch_op.create_unique_constraint('uq_movies_tmdb_mood', ['tmdb_id', 'mood_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_constraint('uq_movies_tmdb_mood', type_='unique')
        batch_op.drop_index(batch_op.f('ix_movies_tmdb_id'))
        batch_op.drop_column('tmdb_id')

    # ### end Alembic commands ###
