"""Ajout du champ poster_url

Revision ID: 979d023dddf6
Revises: 
Create Date: 2025-10-30 12:57:50.602659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '979d023dddf6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('poster_url')

    # ### end Alembic commands ###
