"""Ajout de la colonne photo_url à Profile

Revision ID: dd73ba439e53
Revises: 979d023dddf6
Create Date: 2025-10-31 09:28:54.974498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd73ba439e53'
down_revision = '979d023dddf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('photo_url')

    # ### end Alembic commands ###
